### **Import Libraries**

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

## **KNN Classifier**

In [2]:
class KNNClassifier:

  def coordinat_distance2(self, featers_point1, featers_point2):
    return (featers_point1-featers_point2)**2

  def fit(self, X, y, k):
    self.featers = X
    self.targets = y
    self.k = k

  def predict(self, value):
    # measurement of all distance
    distance_f = np.vectorize(self.coordinat_distance2)
    distance = distance_f(self.featers,value)

    end_distance = []
    for row in range(distance.shape[0]):
      end_distance.append(np.sqrt(np.sum(distance[row])))
    # Find k neiпhbors and return 'k' the most frequent
    end_distance = np.column_stack([np.array(end_distance),self.targets])
    k_neibors = end_distance[end_distance[:,0].argsort()][:self.k]
    return np.argmax(np.bincount(np.int64(k_neibors.T[1])))
  def accuracy_score(self, features, targets):
      answers = []
      for f in features:
        answers.append(self.predict(f))
      return (list(answers == targets).count(True) / len(targets))

### **Simple test**

In [3]:
# Simple value
X_test = np.array([[15,17,19],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y_test = np.array([1,2,2,1,1])

print(np.column_stack([X_test,y_test.T]))

[[15 17 19  1]
 [ 4  5  6  2]
 [ 7  8  9  2]
 [10 11 12  1]
 [13 14 15  1]]


In [4]:
simple_model = KNNClassifier()
simple_model.fit(X_test,y_test,3)
print(simple_model.predict([10,11,12]))

1


### **Iris Test**

In [8]:
dataset = datasets.load_iris()

features_train, features_test, target_train, target_test = train_test_split(dataset['data'], dataset['target'], test_size=0.25, random_state=24)

In [6]:
model = KNNClassifier()
model.fit(features_train,target_train,3)

In [7]:
model.accuracy_score(features_test,target_test)

0.9736842105263158